# Generated by Django 4.0.4 on 2022-12-12 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images')),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
